### ISSUE TITLE
Request to copy/slect function

### ISSUE THREAD

**Issue by mikhoul** [Deliaz/local-storage-explorer#14]
Could you add the possibility yo select and copy the text/data ?

Regards :octocat:

**Comment by Deliaz** [comment]
Thank you for the report. I fixed text selection and released version 1.1.3 to the Chrome Web Store. 
Source code also has been updated.
🍻

**Comment by mikhoul** [comment]
@Deliaz Thanks a lot for your quick reply ! :+1:
